const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const loader=$('#loader');
window.addEventListener('load',()=>setTimeout(()=>loader.classList.add('done'),500));
const progress=$('#progress'), navWrap=$('.nav-wrap');
function scrollUI(){const h=document.documentElement.scrollHeight-innerHeight;progress.style.width=(h>0?scrollY/h*100:0)+'%';navWrap.classList.toggle('scrolled',scrollY>20)}
addEventListener('scroll',scrollUI,{passive:true});scrollUI();
const menu=$('#menuBtn'),links=$('#navLinks');menu.addEventListener('click',()=>{links.classList.toggle('open');menu.innerHTML=links.classList.contains('open')?'<i class="fa-solid fa-xmark"></i>':'<i class="fa-solid fa-bars"></i>'});$$('.nav-links a').forEach(a=>a.addEventListener('click',()=>links.classList.remove('open')));
const theme=$('#themeBtn');const saved=localStorage.getItem('ashim-theme');if(saved==='light')document.body.classList.add('light');function themeIcon(){theme.innerHTML=document.body.classList.contains('light')?'<i class="fa-solid fa-moon"></i>':'<i class="fa-solid fa-sun"></i>'}themeIcon();theme.addEventListener('click',()=>{document.body.classList.toggle('light');localStorage.setItem('ashim-theme',document.body.classList.contains('light')?'light':'dark');themeIcon()});
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');observer.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(e=>observer.observe(e));
const counters=$$('[data-count]');const counterObs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){const el=e.target,target=+el.dataset.count;let start=0;const t0=performance.now();function tick(t){const p=Math.min((t-t0)/900,1);el.textContent=Math.floor(target*(1-Math.pow(1-p,3)));if(p<1)requestAnimationFrame(tick)}requestAnimationFrame(tick);counterObs.unobserve(el)}}),{threshold:.7});counters.forEach(e=>counterObs.observe(e));
if(matchMedia('(pointer:fine)').matches&&!matchMedia('(prefers-reduced-motion:reduce)').matches){const dot=$('#cursorDot'),ring=$('#cursorRing');let mx=innerWidth/2,my=innerHeight/2,rx=mx,ry=my;addEventListener('pointermove',e=>{mx=e.clientX;my=e.clientY;dot.style.left=mx+'px';dot.style.top=my+'px'});function follow(){rx+=(mx-rx)*.16;ry+=(my-ry)*.16;ring.style.left=rx+'px';ring.style.top=ry+'px';requestAnimationFrame(follow)}follow();$$('a,button,.tilt').forEach(el=>{el.addEventListener('mouseenter',()=>{ring.style.width='52px';ring.style.height='52px'});el.addEventListener('mouseleave',()=>{ring.style.width='32px';ring.style.height='32px'})});
$$('[data-tilt]').forEach(card=>{card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(1000px) rotateX(${(-y*5).toFixed(2)}deg) rotateY(${(x*6).toFixed(2)}deg) translateY(-4px)`});card.addEventListener('pointerleave',()=>card.style.transform='')});
$$('.magnetic').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-(r.left+r.width/2))*.12}px,${(e.clientY-(r.top+r.height/2))*.12}px)`});el.addEventListener('pointerleave',()=>el.style.transform='')})}
const lb=$('#lightbox'),img=$('#lightboxImg');$$('.gallery-item').forEach(item=>item.addEventListener('click',()=>{img.src=item.dataset.img;lb.classList.add('open');lb.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}));function close(){lb.classList.remove('open');lb.setAttribute('aria-hidden','true');document.body.style.overflow=''}$('#closeLightbox').addEventListener('click',close);lb.addEventListener('click',e=>{if(e.target===lb)close()});addEventListener('keydown',e=>{if(e.key==='Escape')close()});
$('#year').textContent=new Date().getFullYear();
